pantries/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns(
    'pantries.views',
    (r'^$', 'list'),
    (r'^(?P<pantry_id>\d+)$', 'detail'),
    (r'^new$', 'new'),
    (r'^delete/(?P<pantry_id>\d+)$', 'delete'),
    (r'^(?P<pantry_id>\d+)/add$', 'add_content'),
    (r'^(?P<pantry_id>\d+)/add/(?P<category_id>\d+)$', 'add_content'),
    (r'^(?P<pantry_id>\d+)/add/(?P<category_id>\d+)/(?P<product_id>\d+)$', 'add_content'),
    (r'^(?P<pantry_id>\d+)/delete/(?P<content_id>\d+)$', 'delete_content'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^admin/', include(admin.site.urls)),
    (r'^$', 'blackem.users.views.home'),
    (r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}),
    (r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html',
         'next_page': '/',},
        "logout"),
    (r'^register/$', 'blackem.users.views.register'),
    (r'^products/', include('blackem.products.urls')),
    (r'^pantries/', include('blackem.pantries.urls')),
    (r'^shoppinglists/', include('blackem.shoppinglists.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site-media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': '/home/jani/projects/blackem/site-media',
          'show_indexes': True}),
    )

pantries/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm, ValidationError
from blackem.products.models import Product

class Pantry(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User)

    def __unicode__(self):
        return unicode(self.name)
    
    class Meta:
        verbose_name_plural = "Pantries"

class PantryForm(ModelForm):
    class Meta:
        model = Pantry
        fields = ('name',)

class Content(models.Model):
    pantry = models.ForeignKey(Pantry)
    product = models.ForeignKey(Product)
    amount = models.FloatField()

    def __unicode__(self):
       return u"{0} {1} of {2} in {3}".format(self.amount, self.product.unit,
                                              self.product, self.pantry) 

class ContentForm(ModelForm):
    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount < 0:
            raise ValidationError("No negative amounts.")
        return amount

    class Meta:
        model = Content
        fields = ('amount',)

pantries/views.py
from django.shortcuts import render_to_response, redirect, get_object_or_404, get_list_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.utils import simplejson
from django.http import HttpResponse
from pantries.models import Pantry, Content, PantryForm, ContentForm
from products.models import Product, Category

@login_required
def list(request):
    """List all pantries."""
    pantries = get_list_or_404(Pantry, owner=request.user)
    return render_to_response('pantries/pantry_list.html',
                              {'pantries': pantries})

@login_required
def detail(request, pantry_id):
    """Give detailed view of the pantry.
    
    User can only view their own pantries.

    """
    pantry = get_object_or_404(Pantry, owner=request.user, pk=pantry_id)
    return render_to_response('pantries/pantry_detail.html',
                              {'pantry': pantry})

@login_required
def new(request):
    """Create a new pantry or render appropriate form."""
    if request.method == 'POST':
        form = PantryForm(request.POST)
        if form.is_valid():
            pantry = Pantry(name=form.cleaned_data["name"], owner=request.user)
            pantry.save()
            return redirect('blackem.users.views.home')
    else:
        form = PantryForm()
    return render_to_response('pantries/pantry_form.html',
                              {'form': form},
                             context_instance=RequestContext(request))

@login_required
def delete(request, pantry_id):
    """Delete pantry.

    User can only delete their own pantries.

    """
    Pantry.objects.filter(pk=pantry_id, owner=request.user).delete()
    return redirect('blackem.users.views.home')

@login_required
def add_content(request, pantry_id, category_id=False, product_id=False):
    """Add content to pantry or render appropriate form.

    Content is prompted in three steps:
    1. Ask for a category
    2. Ask for a product in choosen category
    3. Ask for an amount for the choosen product.

    User can only add contents to their own pantries.

    """
    if request.method == 'POST':
        form = ContentForm(request.POST)
        if form.is_valid():
            pantry = get_object_or_404(Pantry,
                                       pk=pantry_id,
                                       owner=request.user)
            product = get_object_or_404(Product, pk=product_id)
            try:
                content = Content.objects.get(pantry=pantry, product=product)
                content.amount += form.cleaned_data['amount']
            except ObjectDoesNotExist:
                content = Content(pantry=pantry,
                                  product=product,
                                  amount=form.cleaned_data['amount'])
            content.save()
        return redirect('pantries.views.detail', pantry_id)

    response_dict = {'pantry_id': pantry_id,
                     'categories': Category.objects.all(),
                     'no_logout': True}
    if category_id:
        response_dict.update(
            {'category_id': category_id,
             'category': Category.objects.get(pk=category_id),
             'products': Product.objects.filter(categories__pk=category_id)}
        )

    if product_id:
        response_dict.update(
            {'form': ContentForm(),
             'product': Product.objects.get(pk=product_id),
             'product_id': product_id}
        )
    return render_to_response('pantries/content_form.html',
                              response_dict,
                              context_instance=RequestContext(request))

@login_required
def delete_content(request, pantry_id, content_id):
    """Delete content from pantry.

    User can only delete content from their own pantries.

    """
    Content.objects.filter(pk=content_id, pantry__owner=request.user).delete()
    return redirect('pantries.views.detail', pantry_id)

templates/pantries/content_form.html
{% extends "base.html" %}

{% block page_title %}add content{% endblock page_title %}

{% block left_col %}
<p>Choose a category:</p>
<ul>
  {% for category in categories %}
  <li><a href="{% url pantries.views.add_content pantry_id=pantry_id, category_id=category.id %}">{{ category }}</a></li>
  {% endfor %}
</ul>

{% if category_id %}
<p>Choose a product from {{ category }}:</p>
<ul>
  {% for product in products %}
  <li><a href="{% url pantries.views.add_content pantry_id=pantry_id, category_id=category_id, product_id=product.id %}">{{ product }}</a></li>
  {% endfor %}
</ul>
{% endif %}

{% if product_id %}
  <form method="post" action="{% url pantries.views.add_content pantry_id=pantry_id, category_id=category_id, product_id=product_id %}"> {% csrf_token %}
  <table>
    <tr><th>{{ form.amount.label_tag }}</th><td>{{ form.amount }}</td><td>of {{ product }}</td></tr>
    <tr><th><input type="submit" value="Submit" /></th></tr>
  </table>
  </form>
{% endif %}
{% endblock left_col %}

templates/pantries/pantry_detail.html
{% extends "base.html" %}

{% block page_title %}pantry {{ pantry }}{% endblock page_title %}

{% block left_col %}
<h1>{{ pantry }}</h1>
<ul>
  {% for content in pantry.content_set.all %}
  <li><a href="/products/{{ content.product.id }}">{{ content.product }}</a>
  {{ content.amount|floatformat }} {{ content.product.unit }}
  <a href="{% url pantries.views.delete_content pantry_id=pantry.id, content_id=content.id %}">
    <img class="action_icon" src="/site-media/remove_icon.png" alt="Delete" />
  </a>
  </li>
  {% endfor %}
  <li>
  <a href="{% url pantries.views.add_content pantry_id=pantry.id %}">
    <img class="action_icon" src="/site-media/add_icon.png" alt="add new content" \>
  </a>
  </li>
</ul>
{% endblock left_col %}
{% block right_col %}
<ul>
  <li>
  <a href="{% url pantries.views.delete pantry_id=pantry.id %}">Delete this pantry.</a>
  </li>
</ul>
{% endblock right_col %}

templates/pantries/pantry_form.html
{% extends "base.html" %}

{% block page_title %}new pantry{% endblock page_title %}

{% block left_col %}
<form method="post" action="{% url pantries.views.new %}"> {% csrf_token %}
<table>
  {{ form.as_table }}
  <tr>
    <th><input type="submit" value="Submit" /></th>
  </tr>
</table>
</form>
{% endblock left_col %}

templates/pantries/pantry_list.html
{% extends "base.html" %}

{% block page_title %}pantries{% endblock page_title %}

{% block left_col %}
<ul>
  {% for pantry in pantries %}
  <li><a href="{% url pantries.views.detail pantry_id=pantry.id %}">{{ pantry }}</a></li>
  {% endfor %}
</ul>
{% endblock left_col %}